Repository govau/furnace, pull requests merged in 2019-05, with the labels that each got.

#89 Add table, security updates
  package-lock.json
  package.json
Labels: enhancement

#88 Tidied up package.json, bumped deps
  package-lock.json
  package.json
Labels: dependencies

#90 Update table to 0.1.2
  package-lock.json
Labels: enhancement

#91 add form, update table
  package-lock.json
  package.json
Labels: bug

#92 add form, update table
  package-lock.json
  package.json
Labels: bug
